[Server]
host=0.0.0.0
port=9500

[Database]
driver=QPSQL
host=80.249.146.54
port=5432
name=plutusbank
user=postgre
password=root

[Logging]
# Файл лога (пустое = только консоль)
file=server.log
# Уровень: debug, info, warning, error
level=debug
# Показывать время в логе
timestamps=true
