[Server]
host=0.0.0.0
port=9500

[Database]
driver=QPSQL
host=127.0.0.1
port=5433
name=plutusbank
user=postgres
password=root

[Logging]
# Файл лога (пустое = только консоль)
file=server.log
# Уровень: debug, info, warning, error
level=debug
# Показывать время в логе
timestamps=true
